
server:
  port: 8080

spring:
  datasource:
    username: root
    password: mysqladmin
    url: jdbc:mysql://localhost:3306/guide?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.javalemon.entity